- hosts: localhost
  become: yes
  tasks:     
  - name: unarchive tar file
    unarchive:
      src: /backup/kafka/kafka_2.13-3.3.1.tgz
      dest: /tmp
      
  - name: move the file
    shell:
      cmd: mv /tmp/kafka_2.13-3.3.1 /usr/bin/kafka
      
  - name: copy kafka service
    copy: 
      src: /backup/kafka/zookeeper.service
      dest: /etc/systemd/system/zookeeper.service
      
  - name: copy kafka service
    copy: 
      src: /backup/kafka/kafka.service
      dest: /etc/systemd/system/kafka.service    
      
  - name: systemctl reload
    become: yes
    systemd:
      daemon_reload: yes
    
  - name: start service
    become: yes
    systemd: 
      name: 
      - zookeeper
      - kafka
      state: started
